name: Node.js Package
on:
    push:
        branches: [ release ]

defaults:
    run:
        working-directory: ./lib

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: yarn install --no-immutable
            # Publish to npm
            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#            # Setup .npmrc file to publish to GitHub Packages
#            - uses: actions/setup-node@v2
#              with:
#                  node-version: '16.x'
#                  registry-url: 'https://npm.pkg.github.com'
#                  scope: '@Camberi'
#            # Publish to GitHub Packages
#            - run: npm publish
#              env:
#                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # Create Git version tag
            - run: npm run createTag
